-- Wag po galawin inaayos ko pa po ito.

INSERT INTO product(Prod_Name, Prod_Desc, Prod_Image, Archived) VALUES
-- Breads
('Almond Bread', 'Made with almond flour and whole almonds, often resulting in a dense, nutty texture. Our bread can be sweet and savory.', 'almondbread.png', 0),
('Cheese Loaf', 'A cheese loaf is processed cheese shaped into a rectangular block for easy slicing, made by blending cheese with salt or emulsifiers for a smooth texture.', 'cheeseloaf.png', 0),
('Coffee Bun', 'Soft, fluffy bun with a coffee-flavored crust, sometimes filled with butter or cream. Perfect for coffee lovers.', 'coffeebun.png', 0),
('Ensaymada', 'A Filipino brioche-like bun topped with buttercream and cheese. Perfect for breakfast or snacks, often paired with coffee or tea.', 'ensaymada.png', 0),
('Garlic Bread', 'Our bread slathered with garlic butter and herbs, then baked or toasted. Aromatic and savory, great as a side or snack.', 'garlicbread.png', 0),
('Ham and Cheese Boat', 'Boat-shaped bread filled with savory ham and melted cheese, often topped with herbs or sauce.', 'hamandcheeseboat.png', 0),
('Korean Garlic Cream Cheese', 'Sweet bun filled with cream cheese and dipped in garlic butter custard. A viral Korean street food snack.', 'koreangarliccreamcheese.png', 0),
('Pizza Sausage', 'Bread or rolls filled or topped with sausage, tomato sauce, cheese, and herbs. A mini pizza experience.', 'pizzasausage.png', 0),
('Pork Floss', 'Dried, shredded pork with a cotton candy-like texture. Made by simmering pork in soy sauce and spices, then shredded and dry-fried until crisp.', 'porkfloss.png', 0),
('Raisin Loaf', 'A sweet or savory bread baked with raisins or other dried fruits mixed into the dough, often enriched with cinnamon or nutmeg.', 'raisinloaf.png', 0),
('Soboro Peanut Bread', 'Korean sweet bun topped with crunchy peanut streusel, sometimes filled with red bean. Soft and nutty.', 'soboropeanutbread.png', 0),
('Spring Roll Floss Overload', 'Crispy spring roll filled or topped with pork or chicken floss, often with mayo or sesame seeds. Crunchy and umami-rich.', 'springrollflossoverload.png', 0),

-- Doughnuts
('Chocolate Donut','A chocolate donut is a sweet, ring-shaped or filled pastry made from dough, typically deep-fried or baked, and coated or infused with chocolate.', 'chocolatedonut.png', 0),
('Chocolate Peanut Donut','A chocolate peanut donut featuring a chocolate glaze or filling with peanut flavors like peanut butter or chopped peanuts.', 'chocolatepeanutdonut.png', 0),
('Glazed Donut','A classic yeast donut coated with a smooth, sweet glaze that adds a glossy finish and a delicate sweetness, complementing the soft, airy texture of the donut.','glazeddonut.png', 0),
('Matcha Donut','A unique donut infused or glazed with matcha, a finely ground green tea powder, offering an earthy, slightly sweet flavor with a vibrant green hue.','matchadonut.png', 0),
('Strawberry Sprinkle Donut','A delightful yeast donut glazed with vibrant strawberry icing and topped with colorful sprinkles, offering a sweet and playful burst of flavor in every bite.', 'strawberrysprinkledonut.png',0),

-- Cakes
('Chiffon Cake','A light, airy cake made with oil, eggs, and flour. Known for its spongy texture and subtle flavor.', 'chiffoncake.png', 0),
('Chocolate Moist Cake','A rich, fudgy cake known for its dense, moist texture, often frosted with chocolate ganache or buttercream.', 'chocolatemoistcake.png', 0),
('Custard Cake','A fluffy chiffon base with a smooth, baked custard topping, offering a creamy, delicate flavor.', 'custardcake.png', 0),
('Mango Cake','A chiffon or sponge cake layered with mango slices and puree. Light and refreshing.', 'mangocake.png', 0),
('Mocha Cake','Infused with coffee and chocolate, layered with mocha buttercream. A treat for coffee lovers.', 'mochacake.png', 0),
('Sansrival Cake','A layered cake of crispy meringue wafers, buttercream, and cashews. Crunchy and indulgent.', 'sansrivalcake.png', 0),
('Yema Cake','A Filipino chiffon cake topped or filled with creamy yema custard made from egg yolks and condensed milk.', 'yemacake.png', 0),

-- Fruit Tea
('Blueberry Soda','A fizzy, refreshing drink with sweet-tart blueberry flavor. Light and fruity.', 'blueberrysoda.png', 0),
('Green Apple Soda','Crisp and tangy soda bursting with green apple flavor. Zesty and fun.', 'greenapplesoda.png', 0),
('Lychee Soda','A sparkling, tropical soda with the delicate, floral sweetness of lychee fruit. Refreshingly light with a hint of exotic fragrance.','lycheesoda.png', 0),
('Strawberry Soda','A sparkling drink with juicy strawberry taste. Perfectly refreshing.', 'strawberrysoda.png', 0),

-- Bites
('Brownies','Dense, fudgy chocolate squares, often studded with nuts or chocolate chips. Baked to a chewy or cakey texture, they’re a rich, indulgent dessert perfect for snacks or gifting.', 'brownies.png', 0),
('Butterscotch','A sweet treat made from brown sugar, butter, and sometimes cream, with a caramel-like, buttery flavor. Often served as bars, squares, or drizzled over desserts.', 'butterscotch.png', 0),
('Chocolate Chip Cookie','A classic, chewy cookie studded with rich chocolate chips, offering a perfect balance of sweet, buttery dough and melty chocolate in every bite.','chocolatechipcookie.png', 0),
('Macarons','Delicate, French-style sandwich cookies with a crisp, smooth shell and a soft, flavorful filling, available in a variety of vibrant colors and flavors like vanilla, chocolate, or fruit.','macarons.png', 0),

-- Milk Tea
('Boba Milktea','A creamy, sweetened tea-based drink blended with milk and chewy tapioca pearls (boba), offering a delightful balance of rich tea flavor and satisfying texture.','bobamilktea.png', 0),
('Matcha Milktea','A smooth, vibrant beverage combining the earthy, slightly bitter notes of matcha green tea with creamy milk, creating a refreshing and subtly sweet drink.','matchamilktea.png', 0);

INSERT INTO category(Cat_Name, Cat_Desc, Archived) VALUES
('Breads', 'A variety of baked goods made from flour and water, often enriched with ingredients like eggs, milk, or butter.', 0),
('Doughnuts', 'Sweet, fried pastries that can be ring-shaped or filled with various sweet fillings.', 0),
('Cakes', 'Sweet baked desserts typically made with flour, sugar, eggs, and butter, often layered or frosted.', 0),
('Fruit Tea', 'Refreshing beverages made with fruit flavors and often carbonated.', 0),
('Bites', 'Small snacks or desserts that are easy to eat in one bite.', 0),
('Milk Tea', 'Tea-based drinks mixed with milk and often served with chewy tapioca pearls.', 0);

INSERT INTO productcategory(Prod_ID, Cat_ID, Archived) VALUES
(1,1,0),
(2,1,0),
(3,1,0),
(4,1,0),
(5,1,0),
(6,1,0),
(7,1,0),
(8,1,0),
(9,1,0),
(10,1,0),
(11,1,0),
(12,1,0),
(13,2,0),
(14,2,0),
(15,2,0),
(16,2,0),
(17,2,0),
(18,3,0),
(19,3,0),
(20,3,0),
(21,3,0),
(22,3,0),
(23,3,0),
(24,3,0),
(25,4,0),
(26,4,0),
(27,4,0),
(28,4,0),
(29,5,0),
(30,5,0),
(31,5,0),
(32,5,0),
(33,6,0),
(34,6,0);

INSERT INTO productstock(Prod_ID, Availability, Archived) VALUES
(1,1,0),
(2,1,0),
(3,1,0),
(4,1,0),
(5,1,0),
(6,1,0),
(7,1,0),
(8,1,0),
(9,1,0),
(10,1,0),
(11,1,0),
(12,1,0),
(13,1,0),
(14,1,0),
(15,1,0),
(16,1,0),
(17,1,0),
(18,1,0),
(19,1,0),
(20,1,0),
(21,1,0),
(22,1,0),
(23,1,0),
(24,1,0),
(25,1,0),
(26,1,0),
(27,1,0),
(28,1,0),
(29,1,0),
(30,1,0),
(31,1,0),
(32,1,0),
(33,1,0),
(34,1,0);

INSERT INTO productprices(Prod_ID, Price, Effective_From, Effective_To, Archived) VALUES
(1, 50.00, '2023-10-01', NULL, 0),
(2, 60.00, '2023-10-02', NULL, 0),
(3, 45.00, '2023-10-03', NULL, 0),
(4, 55.00, '2023-10-04', NULL, 0),
(5, 40.00, '2023-10-05', NULL, 0),
(6, 70.00, '2023-10-06', NULL, 0),
(7, 80.00, '2023-10-07', NULL, 0),
(8, 75.00, '2023-10-08', NULL, 0),
(9, 65.00, '2023-10-09', NULL, 0),
(10, 55.00, '2023-10-10', NULL, 0),
(11, 50.00, '2023-10-11', NULL, 0),
(12, 60.00, '2023-10-12', NULL, 0),
(13, 30.00, '2023-10-13', NULL, 0),
(14, 35.00, '2023-10-14', NULL, 0),
(15, 25.00, '2023-10-15', NULL, 0),
(16, 40.00, '2023-10-16', NULL, 0),
(17, 45.00, '2023-10-17', NULL, 0),
(18, 100.00,'2023-10-18', NULL ,0),
(19, 120.00,'2023-10-19', NULL ,0),
(20, 110.00,'2023-10-20', NULL ,0),
(21, 130.00,'2023-10-21', NULL ,0),
(22, 140.00,'2023-10-22', NULL ,0),
(23, 150.00,'2023-10-23', NULL ,0),
(24,160.00,'2023-10-24',NULL ,0),
(25 ,70.00,'2023-10-25',NULL ,0),
(26 ,80.00,'2023-10-26',NULL ,0),
(27 ,90.00,'2023-10-27',NULL ,0),
(28 ,100.00,'2023-10-28',NULL ,0),
(29 ,20.00,'2023-10-29',NULL ,0),
(30 ,25.00,'2023-10-30',NULL ,0),
(31 ,30.00,'2023-10-31',NULL ,0),
(32 ,35.00,'2023-10-32',NULL ,0),
(33, 50.00, '2023-10-33', NULL, 0),
(34, 60.00, '2023-10-34', NULL, 0);
